<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Test</title>
<script type="text/javascript" src="<?php echo $this->baseurl ; ?>/js/jquery-1.7.1.min.js"></script>
</head>

<body>
<!-- <head> -->
  <?php
  // how to show specific action of specific controller at any template
    //$this->render_action("test","index"); 
  ?>		
<!-- <head> -->

<!-- <body> -->
echo $content_template;
?>
<!-- <body> -->



<!-- <footer> -->

<!-- <footer> -->
